from imported_files.mathmodule import *
num1=int(input("ENTER FIRST NUMBER :"))
num2=int(input("ENTER SECOND NUMBER :"))
data1=add(num1,num2)
print("sum is",data1)
data2=subtract(num1,num2)
print("Difference is",data2)
data3=multiply(num1,num2)
print("product is",data3)
data4=divide(num1,num2)
print("Quotient is",data4)
data5=modulus(num1,num2)
print("Modulus is",data5)